---
- hosts: all
  become: true
  tasks:
    - debug:
        msg: "demarrage {{ PWD }}"
    - name: current_working_directory
      shell: pwd
      register: current_working_directory
    - name: load
      include_vars:
        file: "{{ PWD }}/deployment/prod.properties"
    - debug:
        msg: "{{ inventory_hostname }} and {{ ids }}"
    - name: build config file from template
      vars:
          host_id: "{{ ids[inventory_hostname].value }}"
      template:
        src: ../config/config.yaml.template
        dest: ~{{ user_to_create }}/config/config.yaml
        owner: "{{ user_to_create }}"
        mode: 0666
    - name: clean logs
      shell: "/bin/rm -rf ~{{ user_to_create }}/logs/*.log"      
    - name: build bin file from template
      template:
        src: ../bin/run.sh.template
        dest: ~{{ user_to_create }}/bin/run.sh
        owner: "{{ user_to_create }}"
        mode: 0755
    - name: build bin file from template
      template:
        src: ../bin/kill.sh.template
        dest: ~{{ user_to_create }}/bin/kill.sh
        owner: "{{ user_to_create }}"
        mode: 0755
    - name: build bin file from template
      template:
        src: ../config/log4j.xml.template
        dest: ~{{ user_to_create }}/config/log4j.xml
        owner: "{{ user_to_create }}"
        mode: 0744
    - name: build client_jaas file from template
      template:
        src: ../config/client_jaas.conf.template
        dest: ~{{ user_to_create }}/config/client_jaas.conf
        owner: "{{ user_to_create }}"
        mode: 0644
    - name: Deploy key tab file
      copy:
        src: ../../WorkFlow/ansible/tools/application/keytabs/{{ user_to_create }}.keytab
        dest: ~{{ user_to_create }}/config/{{ user_to_create }}.keytab
        owner: "{{ user_to_create }}"
        mode: 0600
    - name: Copy jars
      copy:
        src: "{{ PWD }}/target/{{ jar_name }}"
        dest: ~{{ user_to_create }}/lib
      when:  inventory_hostname == "ipc0"
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"
    ids:
      ipc0:
        value: 1
      ipc1:
        value: 2
      ipc2:
        value: 3
      ipc3:
        value: 4
      ipc5:
        value: 5
      ipc6:
        value: 6
      ipc7:
        value: 7
      ipc8:
        value: 8
  
