{
 "title": "System & Kafka dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hosts", "query": "label_values(host)" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_load1{host=~\"[[hosts]]\"}) by (host) / (count(cpu_usage_idle) by (host) - 1.0)",
     "legendFormat": "{{ host }} load_average1"
    },
    {
     "expr": "avg(system_load5{host=~\"[[hosts]]\"}) by (host) / (count(cpu_usage_idle) by (host) - 1.0)",
     "legendFormat": "{{ host }} load_average5"
    },
    {
     "expr": "avg(system_load15{host=~\"[[hosts]]\"}) by (host) / (count(cpu_usage_idle) by (host) - 1.0)",
     "legendFormat": "{{ host }} load_average15"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"[[hosts]]\"}",
     "legendFormat": "{{ host }} memory used total"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-cpu_usage_idle{host=~\"[[hosts]]\",cpu='cpu-total'}",
     "legendFormat": "{{ host }} cpu used total"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(net_bytes_recv{host=~\"[[hosts]]\"}[1m])) by (host)",
     "legendFormat": "{{ host }} recv"
    },
    {
     "expr": "sum(rate(net_bytes_sent{host=~\"[[hosts]]\"}[1m])) by (host)",
     "legendFormat": "{{ host }} sent"
    }
   ]
  },
  {
   "title": "DISK I/O (reads/writes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(diskio_read_bytes{host=~\"[[hosts]]\"}[1m])) by (host)",
     "legendFormat": "{{host}} total read bytes"
    },
    {
     "expr": "sum(rate(diskio_write_bytes{host=~\"[[hosts]]\"}[1m])) by (host)",
     "legendFormat": "{{ host }} total write bytes"
    }
   ]
  },
  {
   "title": "DISK I/O operations in progress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(diskio_iops_in_progress{host=~\"[[hosts]]\"}) by (host)",
     "legendFormat": "{{ host }} total iops in progress"
    }
   ]
  },
  { "title": "Kafka broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Produce request rate by topic",
   "type": "graph",
   "description": "TotalProduceRequestsPerSec",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalproducerequests_total{topic != \"\"}[1m])",
     "legendFormat": "({{ instance }} - topic:  {{ topic }}) success"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedproducerequests_total{topic != \"\"}[1m])",
     "legendFormat": "({{ instance }} - topic:  {{ topic }}) errors"
    }
   ]
  },
  {
   "title": "Consume request rate by topic",
   "type": "graph",
   "description": "TotalFetchRequestsPerSec",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic != \"\"}[1m])",
     "legendFormat": "({{ instance }} - topic:  {{ topic }}) success"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{topic != \"\"}[1m])",
     "legendFormat": "({{ instance }} - topic:  {{ topic }}) errors"
    }
   ]
  },
  {
   "title": "Kafka network total request rate",
   "type": "graph",
   "description": "kafka.network:type=RequestMetrics,name=RequestsPerSec,request={Produce|FetchConsumer|FetchFollower}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{request=~\"Produce|FetchConsumer|FetchFollower\"}[1m])",
     "legendFormat": "({{ instance }}) {{ request }}"
    }
   ]
  },
  {
   "title": "Size of the request queue",
   "type": "graph",
   "description": "RequestQueueSize\n\nA congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize",
     "legendFormat": "({{ instance }}) size"
    }
   ]
  },
  {
   "title": "ZooKeeper client sync rate",
   "type": "graph",
   "description": "ZooKeeperSyncConnectsPerSec\nZooKeeper client is connected to the ensemble and ready to execute operations.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeepersyncconnects_total[1m])",
     "legendFormat": "{{ instance }} {{ request }}"
    }
   ]
  },
  { "title": "Kafka producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg",
     "legendFormat": "({{ instance }}) latency avg"
    },
    {
     "expr": "kafka_producer_request_latency_max",
     "legendFormat": "({{ instance }}) latency max"
    }
   ]
  },
  {
   "title": "Request & response rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kafka_producer_request_rate", "legendFormat": "({{ instance }}) request" },
    { "expr": "kafka_producer_response_rate", "legendFormat": "({{ instance }}) response" }
   ]
  },
  { "title": "Kafka consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Records lag max",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_consumer_records_lag_max", "legendFormat": "({{ instance }}) lag max" }
   ]
  },
  {
   "title": "Average  bytes consumed per second.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_bytes_consumed_rate",
     "legendFormat": "({{ instance }}) bytes rate"
    }
   ]
  },
  {
   "title": "Average  records consumed per second.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_rate",
     "legendFormat": "({{ instance }}) records rate"
    }
   ]
  },
  {
   "title": "Fetch requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kafka_consumer_fetch_rate", "legendFormat": "({{ instance }}) fetch rate" }
   ]
  },
  {
   "title": "Time for a fetch request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg",
     "legendFormat": "({{ instance }}) latency avg"
    },
    {
     "expr": "kafka_consumer_fetch_latency_max",
     "legendFormat": "({{ instance }}) latency max"
    }
   ]
  },
  {
   "title": "Average throttle time",
   "type": "graph",
   "description": "When quotas are enabled, the broker may delay fetch requests in order to throttle a consumer which has exceeded its limit. This metric indicates how throttling time has been added to fetch requests on average.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_throttle_time_avg",
     "legendFormat": "({{ instance }}) throttle time avg"
    },
    {
     "expr": "kafka_consumer_fetch_throttle_time_max",
     "legendFormat": "({{ instance }}) throttle time  max"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_count",
     "legendFormat": "({{ instance }}) connections"
    }
   ]
  },
  {
   "title": "New established connections rate",
   "type": "graph",
   "description": "New connections established per second in the window.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_connection_creation_rate",
     "legendFormat": "({{ instance }}) connection rate"
    }
   ]
  }
 ]
}