- hosts: ipc6
  become: true
  tasks:
    - debug:
        msg: create kerberos
    - name: del princip
      shell: kadmin.local -q 'delprinc -force  kafka/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - ipc9
        - ipc10
        - ipc11
        - ipc12
        - ipc13
        - ipc14
        - ipc15
        - ipc16
    - name: rm keytab
      shell: rm -f /home/user/keytabs/kafka_{{ item }}.keytab
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - ipc9
        - ipc10
        - ipc11
        - ipc12
        - ipc13
        - ipc14
        - ipc15
        - ipc16
    - name: ADd princip
      shell: kadmin.local -q 'addprinc  -pw kafka kafka/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - ipc9
        - ipc10
        - ipc11
        - ipc12
        - ipc13
        - ipc14
        - ipc15
        - ipc16
    - name: create keytab
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/kafka_all.keytab  kafka/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - ipc9
        - ipc10
        - ipc11
        - ipc12
        - ipc13
        - ipc14
        - ipc15
        - ipc16
    - name: get keytab
      fetch:
        src: /home/user/keytabs/kafka_all.keytab
        dest: ./tools/kafka/
        flat: yes
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"