- hosts: ipc6
  become: true
  tasks:
    - debug:
        msg: create kerberos
    - name: del princip dn
      shell: kadmin.local -q 'delprinc -force  dn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: del princip nn
      shell: kadmin.local -q 'delprinc -force  nn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master

    - name: del princip nm
      shell: kadmin.local -q 'delprinc -force  nm/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: del princip rm
      shell: kadmin.local -q 'delprinc -force  rm/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: del princip sn
      shell: kadmin.local -q 'delprinc -force  sn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: del princip jn
      shell: kadmin.local -q 'delprinc -force  jn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: del princip host
      shell: kadmin.local -q 'delprinc -force  host/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_nn.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_dn.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_nm.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/spnego.service.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_sn.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_jn.keytab
    - name: rm keytab
      shell: rm -f /home/user/keytabs/hdfs_all_rm.keytab

    - name: add princip rm
      shell: kadmin.local -q 'addprinc  -pw rm rm/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip dn
      shell: kadmin.local -q 'addprinc  -pw dn dn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip jn
      shell: kadmin.local -q 'addprinc  -pw jn jn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip nn
      shell: kadmin.local -q 'addprinc  -pw nn nn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip nm
      shell: kadmin.local -q 'addprinc  -pw nm nm/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip sn
      shell: kadmin.local -q 'addprinc  -pw sn sn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: add princip jn
      shell: kadmin.local -q 'addprinc  -pw jn jn/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: ADd princip host
      shell: kadmin.local -q 'addprinc  -pw host host/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: ADd princip HTTP
      shell: kadmin.local -q 'addprinc  -pw HTTP HTTP/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_dn -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_dn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  dn/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_dn -2
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_dn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_nn -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_nn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  nn/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_nn -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_nn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_nm -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_nm.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  nm/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_nm -2
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_nm.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_sn -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_sn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  sn/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_sn -2
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_sn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_jn -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_jn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  jn/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_jn -2
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_jn.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_rm -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_rm.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  rm/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: create keytab hdfs_all_rm -2
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/hdfs_all_rm.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  host/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master        
    - name: create keytab spnego.service.keytab -1
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/spnego.service.keytab -e aes256-cts-hmac-sha1-96:normal,aes128-cts-hmac-sha1-96:normal,arcfour-hmac-md5:normal  HTTP/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc3
        - ipc4
        - ipc5
        - ipc6
        - ipc7
        - ipc8
        - hadoop-master
    - name: get keytab hdfs_all_nn.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_nn.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab hdfs_all_dn.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_dn.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab hdfs_all_nm.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_nm.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab  spnego.service.keytab
      fetch:
        src: /home/user/keytabs/spnego.service.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab  hdfs_all_sn.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_sn.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab  hdfs_all_jn.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_jn.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
    - name: get keytab  hdfs_all_rm.keytab
      fetch:
        src: /home/user/keytabs/hdfs_all_rm.keytab
        dest: ./tools/hadoop/keytabs/
        flat: yes
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"