- hosts: ipc6
  become: true
  tasks:
    - debug:
        msg: create kerberos
    - name: del princip
      shell: kadmin.local -q 'delprinc -force  zookeeper/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc6
        - ipc7
        - ipc8
    - name: rm keytab
      shell: rm -f /home/user/keytabs/zookeeper.keytab
    - name: ADd princip
      shell: kadmin.local -q 'addprinc  -pw zookeeper zookeeper/{{ item }}@GS.COM' 
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc6
        - ipc7
        - ipc8
    - name: create keytab
      shell: kadmin.local -q 'ktadd -k /home/user/keytabs/zookeeper.keytab  zookeeper/{{ item }}@GS.COM'
      loop:
        - ipc0
        - ipc1
        - ipc2
        - ipc6
        - ipc7
        - ipc8
    - name: get keytab
      fetch:
        src: /home/user/keytabs/zookeeper.keytab
        dest: ./tools/zookeeper/
        flat: yes
  vars:
    ansible_become_pass: granada01
    user_to_create: zookeeper
    PWD: "{{ lookup('env', 'PWD') }}"
