- hosts: ipc0,ipc1,ipc2,ipc7,ipc8
  become: true
  tasks:
    - debug:
        msg: Install ZOOKEEPER
    - user:
        name: "{{ user_to_create }}"
        group: nogroup
        shell: /bin/bash
        createhome: yes
        home: /home/zookeeper
    - name: stop zookeeper service
      shell: "systemctl stop zookeeper"
      ignore_errors: yes
    - name: Download zookeeper {{ zookeeper_version }}
      get_url: 
        url: https://downloads.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
        owner: "{{ user_to_create }}"
        dest: "{{ zookeeper_install_folder }}/zookeeper-{{ zookeeper_version }}-bin.tgz"
        mode: 0644
        force: no
    - name: Unpack the tar
      unarchive:
        src: "{{ zookeeper_install_folder }}/zookeeper-{{ zookeeper_version }}-bin.tgz"
        dest: "{{ zookeeper_install_folder }}"
        remote_src: true
    - name: remove symlink {{ zookeeper_install_folder }}/latest to this version
      file:
        path: "{{ zookeeper_install_folder }}/latest"
        state: absent
    - name: create /home/zookeeper/data
      file:
        path: "/home/zookeeper/data"
        state: directory
        owner: "{{ user_to_create }}"
    - name: copy myid
      vars:
        Zookeeper_id: "{{ zk_hosts[inventory_hostname].id }}"
      template:
        src: ./tools/zookeeper/myid
        dest: "/home/zookeeper/data/"
        mode: 0644
        owner: "{{ user_to_create }}"

    - name: Symlink {{ zookeeper_install_folder }}/latest to this version
      file:
        path: "{{ zookeeper_install_folder }}"
        src: "{{ zookeeper_install_folder }}/apache-zookeeper-{{ zookeeper_version }}-bin"
        dest: "{{ zookeeper_install_folder }}/latest"
        owner: "{{ user_to_create }}"
        state: link
        force: yes
    - name: chown
      shell: " chown -R {{ user_to_create }}:nogroup {{ zookeeper_install_folder }}/apache-zookeeper-{{ zookeeper_version }}-bin"
    - name: copy zoo.cfg
      copy:
        src: ./tools/zookeeper/zoo.cfg
        dest: "{{ zookeeper_install_folder }}/latest/conf/zoo.cfg"
        mode: 0644
    - name: copy client_jaas.conf
      vars:
        Zookeeper_host: "{{ zk_hosts[inventory_hostname].value }}"
      template:
        src: ./tools/zookeeper/client_jaas.conf
        dest: "{{ zookeeper_install_folder }}/latest/conf/client_jaas.conf"
        mode: 0644
    - name: copy environment
      copy:
        src: ./tools/zookeeper/zookeeper-env.sh
        dest: "{{ zookeeper_install_folder }}/latest/conf/zookeeper-env.sh"
        mode: 0644
    - name: copy log4j
      copy:
        src: ./tools/zookeeper/log4j.properties
        dest: "{{ zookeeper_install_folder }}/latest/conf/log4j.properties"
        mode: 0644

    - name: copy zookeeper.keytab
      vars:
        Zookeeper_id: "{{ zk_hosts[inventory_hostname].id }}"
      copy:
        owner: zookeeper
        src: ./tools/zookeeper/zookeeper.keytab
        dest: "{{ zookeeper_install_folder }}/latest/conf/zookeeper.keytab"
        mode: 0600
    - name: copy zookeeper.service
      copy:
        owner: zookeeper
        src: ./tools/zookeeper/zookeeper.service
        dest: "/etc/systemd/system/zookeeper.service"
        mode: 0644
    - name: reload zookeeper.service   
      command: systemctl daemon-reload 
    - name: start zookeeper service
      shell: "systemctl start zookeeper"
    - name: start zookeeper service
      shell: "systemctl enable zookeeper"

  vars:
    ansible_become_pass: granada01
    user_to_create: zookeeper
    PWD: "{{ lookup('env', 'PWD') }}"
    zookeeper_install_folder: /home/zookeeper
    zookeeper_version: 3.7.0
    
    
    PWD: "{{ lookup('env', 'PWD') }}"
    zk_hosts:
      ipc0:
        value: ipc0
        id: 1
      ipc1:
        value: ipc1
        id: 2
      ipc2:
        value: ipc2
        id: 3
      ipc7:
        value: ipc7
        id: 4
      ipc8:
        value: ipc8
        id: 5
