- hosts: all
  become: true
  tasks:
    - name: Install default JRE
      apt:
        name:
          -  default-jre
    - name: "Download"
      include_tasks: install-single-java.yml
      loop: "{{ jdks | dict2items }}"
    - name: Correct java version selected
      alternatives:
        name: java
        path: /usr/lib/jvm/jdk8u275-b01/bin/java
    - name: create link to java 8
      file:
        src: "/usr/lib/jvm/jdk8u275-b01"
        dest: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
        state: link
    - name: create link to java 15
      file:
        src: "/usr/lib/jvm/jdk-15.0.1+9"
        dest: "/usr/lib/jvm/jdk-15"
        state: link
    - name: create link to java 13
      file:
        src: "/usr/lib/jvm/jdk-13.0.2+8"
        dest: "/usr/lib/jvm/jdk-13"
        state: link
  vars:
    ansible_become_pass: granada01
    jdks:
      java_jdk_8: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u275-b01/OpenJDK8U-jdk_x64_linux_hotspot_8u275b01.tar.gz
      java_jdk_13: https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_linux_hotspot_13.0.2_8.tar.gz
      java_jdk_15: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz