all:
  hosts:
    ipc0:
    ipc1:
    ipc2:
    ipc3:
    ipc5:
    ipc6:
    ipc7:
    ipc8:
  children:
    ignite:
      hosts:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_hbase:
      hosts:
        ipc1:
        ipc2:
        ipc3:
        ipc6:
        ipc7:
        ipc8:
    wf_archive:
      hosts:
        ipc0:
        ipc1:
        ipc2:
        ipc3:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_copy_files:
      hosts:
        ipc0:
        ipc1:
        ipc2:
        ipc3:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_cmp_hashkey:
      hosts:
        ipc0:
        ipc2:
        ipc5:
        ipc7:
        ipc8:
    wf_dupcheck:
      hosts:
        ipc1:
        ipc3:
    wf_ext_img_infos:
      hosts:
        ipc0:
        ipc1:
        ipc2:
        ipc3:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_proc_and_publish_photo:
      hosts:
        ipc1:
        ipc3:
        ipc6:
        ipc8:
    wf_proc_and_publish_exif_data:
      hosts:
        ipc1:
        ipc2:
        ipc3:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_scan:
      hosts:
        ipc0:
        ipc1:
        ipc2:
        ipc3:
        ipc5:
        ipc6:
        ipc7:
        ipc8:
    wf_storm:
      hosts:
        ipc0:
#        ipc1:
#        ipc2:
#        ipc3:
#        ipc5:
#        ipc6:
#        ipc7:
#        ipc8:
    wf_monitor:
      hosts:
        ipc7:
        ipc8:
  vars:
    ansible_user: user
    ansible_ssh_private_key_file: /etc/gitlab/ssh-keys/private-key-1