---
- hosts: all
  become: true
  tasks:
    - debug:
        msg: "demarrage {{ PWD }}"
    - name: build run.sh from template
      copy:
        src: ./tools/kafka/run.sh
        dest: "{{ kafka_install_folder }}/latest/bin/run.sh"
        owner: root
        mode: 0755
    - name: current_working_directory
      shell: pwd
      register: current_working_directory
    - name: Start kafka
      shell: "systemctl restart kafka.service"
  vars:
    ansible_become_pass: granada01
    PWD: "{{ lookup('env', 'PWD') }}"
    kafka_install_folder: /opt/kafka
