- hosts: all
  become: true
  tasks:
    - debug:
        msg: Start  Kafka nrokers
    - name: start kafka service
      shell: systemctl start kafka.service 
  vars:
    ansible_become_pass: granada01
