enum Actions {
    UNDEFINED,
    LOAD_IMAGES,
    LOAD_IMAGES_OF_KEYWORD,
    IMAGES_LOADING,
    LAST_IMAGES_LOADING,
    IMAGES_ARE_LOADED,
    RATINGS_ARE_LOADED,
    RATINGS_ARE_LOADING,
    ADDING_KEYWORDS,
    DELETE_KEYWORDS,
    LOAD_ALL_KEYWORDS,
    ALL_KEYWORDS_ARE_LOADED,
    UPDATE_IMAGES,
    DELETE_IMAGE,
    SELECT_IMAGE,
    EXIF_ARE_LOADING,
    EXIF_ARE_LOADED,
    IMAGE_IS_LOADED,
    UNDO_DELETE_IMAGE,
    NEXT_IMAGE,
    PREV_IMAGE,
    SAVE_IMAGE,
    LOADING_SELECTED_IMAGE_TO_DISPLAY,
    SELECTED_IMAGE_TO_DISPLAY_IS_LOADED,
    DESELECT_IMAGE_TO_DISPLAY
}

export default Actions;
