# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########### These MUST be filled in for a storm configuration
storm.zookeeper.servers:
 - ipc0
 - ipc1
 - ipc2
 - ipc7
 - ipc8
 
storm.local.dir: "/home/storm/local"
storm.log.dir: "/home/storm/latest/logs"
storm.log4j2.conf.dir: "log4j2"

nimbus.seeds: ["IPC1"]

nimbus.thrift.port: 49625
supervisor.slots.ports:
- 6700


ui.host: 0.0.0.0
ui.port: 8085
logviewer.port: 8086
nimbus.thrift.max_buffer_size: 104857600

supervisor.childopts: "-Xmx256m"
supervisor.run.worker.as.user: true
supervisor.worker.launcher: /home/storm/worker-launch/worker-launcher
topology.submitter.user: wf_storm
nimbus.supervisor.users: ["storm","wf_storm"]
nimbus.admins: ["storm"]
storm.principal.tolocal: "org.apache.storm.security.auth.KerberosPrincipalToLocal"
storm.thrift.transport: "org.apache.storm.security.auth.kerberos.KerberosSaslTransportPlugin"
supervisor.heartbeat.frequency.secs: 120
worker.heartbeat.frequency.secs: 5
supervisor.thrift.threads: 4

java.security.auth.login.config: "/home/storm/latest/conf/client_jaas.conf"
nimbus.childopts: "-Xmx512m -Djava.security.auth.login.config=/home/storm/latest/conf/client_jaas.conf"
ui.childopts: "-Xmx768m -Djava.security.auth.login.config=/home/storm/latest/conf/client_jaas.conf"
supervisor.childopts: "-Xmx256m -Djava.security.auth.login.config=/home/storm/latest/conf/client_jaas.conf "
storm.zookeeper.superACL: "sasl:storm"

worker.heap.memory.mb: 1512
worker.childopts: "-Djava.security.auth.login.config=/home/wf_storm/config/client_jaas.conf -Dlog4j.configurationFile=/home/wf_storm/config/log4j.xml -Xmx1512m -XX:+PrintGCDetails -Xloggc:artifacts/gc.log -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"


storm.messaging.netty.server_worker_threads: 5
storm.messaging.netty.client_worker_threads: 5

supervisor.monitor.frequency.secs: 30
supervisor.worker.timeout.secs: 180
worker.max.timeout.secs: 180
topology.worker.receiver.thread.count: 5
storm.scheduler: "org.apache.storm.scheduler.DefaultScheduler"
# 
# 
# ##### These may optionally be filled in:
#    
## List of custom serializations
# topology.kryo.register:
#     - org.mycompany.MyType
#     - org.mycompany.MyType2: org.mycompany.MyType2Serializer
#
## List of custom kryo decorators
# topology.kryo.decorators:
#     - org.mycompany.MyDecorator
#
## Locations of the drpc servers
# drpc.servers:
#     - "server1"
#     - "server2"

## Metrics Consumers
## max.retain.metric.tuples
## - task queue will be unbounded when max.retain.metric.tuples is equal or less than 0.
## whitelist / blacklist
## - when none of configuration for metric filter are specified, it'll be treated as 'pass all'.
## - you need to specify either whitelist or blacklist, or none of them. You can't specify both of them.
## - you can specify multiple whitelist / blacklist with regular expression
## expandMapType: expand metric with map type as value to multiple metrics
## - set to true when you would like to apply filter to expanded metrics
## - default value is false which is backward compatible value
## metricNameSeparator: separator between origin metric name and key of entry from map
## - only effective when expandMapType is set to true
# topology.metrics.consumer.register:
#   - class: "org.apache.storm.metric.LoggingMetricsConsumer"
#     max.retain.metric.tuples: 100
#     parallelism.hint: 1
#   - class: "org.mycompany.MyMetricsConsumer"
#     max.retain.metric.tuples: 100
#     whitelist:
#       - "execute.*"
#       - "^__complete-latency$"
#     parallelism.hint: 1
#     argument:
#       - endpoint: "metrics-collector.mycompany.org"
#     expandMapType: true
#     metricNameSeparator: "."

## Cluster Metrics Consumers
# storm.cluster.metrics.consumer.register:
#   - class: "org.apache.storm.metric.LoggingClusterMetricsConsumer"
#   - class: "org.mycompany.MyMetricsConsumer"
#     argument:
#       - endpoint: "metrics-collector.mycompany.org"
#
# storm.cluster.metrics.consumer.publish.interval.secs: 60

# Event Logger
# topology.event.logger.register:
#   - class: "org.apache.storm.metric.FileBasedEventLogger"
#   - class: "org.mycompany.MyEventLogger"
#     arguments:
#       endpoint: "event-logger.mycompany.org"

# Metrics v2 configuration (optional)
#storm.metrics.reporters:
#  # Graphite Reporter
#  - class: "org.apache.storm.metrics2.reporters.GraphiteStormReporter"
#    daemons:
#        - "supervisor"
#        - "nimbus"
#        - "worker"
#    report.period: 60
#    report.period.units: "SECONDS"
#    graphite.host: "localhost"
#    graphite.port: 2003
#
#  # Console Reporter
#  - class: "org.apache.storm.metrics2.reporters.ConsoleStormReporter"
#    daemons:
#        - "worker"
#    report.period: 10
#    report.period.units: "SECONDS"
#    filter:
#        class: "org.apache.storm.metrics2.filters.RegexFilter"
#        expression: ".*my_component.*emitted.*"
